// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOrphan(arg1) {
  return window['go']['main']['App']['DeleteOrphan'](arg1);
}

export function RequestConfirmation(arg1, arg2) {
  return window['go']['main']['App']['RequestConfirmation'](arg1, arg2);
}

export function ScanOrphans() {
  return window['go']['main']['App']['ScanOrphans']();
}
