// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {steam} from '../models';

export function DeleteOrphan(arg1:string):Promise<void>;

export function RequestConfirmation(arg1:string,arg2:string):Promise<boolean>;

export function ScanOrphans():Promise<Array<steam.AppInfo>>;
